name: Scrapping

on:
  schedule:
    - cron: '0 0 * *'
  workflow_dispatch:
  
jobs:
  Komik-Scrape:
    runs-on: windows-latest
    env :
      ATLAS_URL: ${{ secrets.ATLAS_URL }}
      ATLAS_COLLECTION: ${{ secrets.ATLAS_COLLECTION }}
      ATLAS_DB: ${{ secrets.ATLAS_DB }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install packages
        run: |
          install.packages("rvest", dependencies = TRUE)
          install.packages("tidyverse", dependencies = TRUE)
          install.packages("mongolite")
        shell: Rscript {0}
      - name: Scrape Data Komik to MongoDB Atlas
        run: Komik_scrape.R
